version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: paycanvas-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${PAYCANVAS_DB_NAME:-paycanvas_dev}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PAYCANVAS_DB_USER:-paycanvas}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
